name: reviewdog
on: [pull_request]
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.x'
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
